import type { DrawData } from "@/lib/types";
import type { RegattaDay } from "@/lib/regatta-days";
import { compareEventsForSelector } from "@/config/event-selector-groups";
import grandDraw from "@/data/grand-2026-draw.json";
import remenhamDraw from "@/data/remenham-2026-draw.json";
import lpDraw from "@/data/lp-2026-draw.json";
import bridgeDraw from "@/data/bridge-2026-draw.json";
import thamesDraw from "@/data/thames-2026-draw.json";
import wargraveDraw from "@/data/wargrave-2026-draw.json";
import templeDraw from "@/data/temple-2026-draw.json";
import islandDraw from "@/data/island-2026-draw.json";
import peDraw from "@/data/pe-2026-draw.json";
import prince_philipDraw from "@/data/prince-philip-2026-draw.json";
import stewardsDraw from "@/data/stewards-2026-draw.json";
import townDraw from "@/data/town-2026-draw.json";
import visitorsDraw from "@/data/visitors-2026-draw.json";
import wyfoldDraw from "@/data/wyfold-2026-draw.json";
import queen_motherDraw from "@/data/queen-mother-2026-draw.json";
import princess_graceDraw from "@/data/princess-grace-2026-draw.json";
import powDraw from "@/data/pow-2026-draw.json";
import princess_of_walesDraw from "@/data/princess-of-wales-2026-draw.json";
import danesfieldDraw from "@/data/danesfield-2026-draw.json";
import queen_victoriaDraw from "@/data/queen-victoria-2026-draw.json";
import fawleyDraw from "@/data/fawley-2026-draw.json";
import diamond_jubileeDraw from "@/data/diamond-jubilee-2026-draw.json";
import britanniaDraw from "@/data/britannia-2026-draw.json";
import prince_albertDraw from "@/data/prince-albert-2026-draw.json";
import gobletsDraw from "@/data/goblets-2026-draw.json";
import hambleden_pairsDraw from "@/data/hambleden-pairs-2026-draw.json";
import double_scullsDraw from "@/data/double-sculls-2026-draw.json";
import stonorDraw from "@/data/stonor-2026-draw.json";
import diamondDraw from "@/data/diamond-2026-draw.json";
import princess_royalDraw from "@/data/princess-royal-2026-draw.json";

export type EventCategory =
  | "premier-mens-eights"
  | "premier-womens-eights"
  | "intermediate-mens-eights"
  | "intermediate-mens-coxless-fours"
  | "intermediate-womens-eights"
  | "intermediate-quads"
  | "club-eights"
  | "club-fours"
  | "student-eights"
  | "student-fours"
  | "junior-eights"
  | "junior-quads"
  | "open"
  | string;

export type EventId = "grand" | "remenham" | "lp" | "bridge" | "thames" | "wargrave" | "temple" | "island" | "pe" | "prince-philip" | "stewards" | "town" | "visitors" | "wyfold" | "queen-mother" | "princess-grace" | "pow" | "princess-of-wales" | "danesfield" | "queen-victoria" | "fawley" | "diamond-jubilee" | "britannia" | "prince-albert" | "goblets" | "hambleden-pairs" | "double-sculls" | "stonor" | "diamond" | "princess-royal";

export interface EventConfig {
  id: EventId;
  trophySlug: string;
  timetableCodes: string[];
  year: number;
  displayName: string;
  shortLabel: string;
  headerSubtitle: string;
  crewCount: number;
  draw: DrawData;
  raceDays: RegattaDay[];
  roundSizes: readonly number[];
  roundLabels: string[];
  seededCrewNumbers: readonly number[];
  seededCrewNames: readonly string[];
  noRacingNote?: string;
  category: EventCategory;
}

const PE_RACE_DAYS: RegattaDay[] = [
  { id: "tue", label: "Tuesday 30 June", shortLabel: "Tue", isoDate: "2026-06-30", primaryRoundIndex: 0 },
  { id: "wed", label: "Wednesday 1 July", shortLabel: "Wed", isoDate: "2026-07-01", primaryRoundIndex: 1 },
  { id: "fri", label: "Friday 3 July", shortLabel: "Fri", isoDate: "2026-07-03", primaryRoundIndex: 2 },
  { id: "sat", label: "Saturday 4 July", shortLabel: "Sat", isoDate: "2026-07-04", primaryRoundIndex: 3 },
  { id: "sun", label: "Sunday 5 July", shortLabel: "Sun", isoDate: "2026-07-05", primaryRoundIndex: 4 },
];

const POW_RACE_DAYS: RegattaDay[] = [
  { id: "thu", label: "Thursday 2 July", shortLabel: "Thu", isoDate: "2026-07-02", primaryRoundIndex: 0 },
  { id: "fri", label: "Friday 3 July", shortLabel: "Fri", isoDate: "2026-07-03", primaryRoundIndex: 1 },
  { id: "sat", label: "Saturday 4 July", shortLabel: "Sat", isoDate: "2026-07-04", primaryRoundIndex: 2 },
  { id: "sun", label: "Sunday 5 July", shortLabel: "Sun", isoDate: "2026-07-05", primaryRoundIndex: 3 },
];

const GOBLETS_RACE_DAYS: RegattaDay[] = [
  { id: "thu", label: "Thursday 2 July", shortLabel: "Thu", isoDate: "2026-07-02", primaryRoundIndex: 0 },
  { id: "fri", label: "Friday 3 July", shortLabel: "Fri", isoDate: "2026-07-03", primaryRoundIndex: 1 },
  { id: "sat", label: "Saturday 4 July", shortLabel: "Sat", isoDate: "2026-07-04", primaryRoundIndex: 2 },
  { id: "sun", label: "Sunday 5 July", shortLabel: "Sun", isoDate: "2026-07-05", primaryRoundIndex: 3 },
];

const LP_RACE_DAYS: RegattaDay[] = [
  { id: "thu", label: "Thursday 2 July", shortLabel: "Thu", isoDate: "2026-07-02", primaryRoundIndex: 0 },
  { id: "fri", label: "Friday 3 July", shortLabel: "Fri", isoDate: "2026-07-03", primaryRoundIndex: 1 },
  { id: "sat", label: "Saturday 4 July", shortLabel: "Sat", isoDate: "2026-07-04", primaryRoundIndex: 2 },
  { id: "sun", label: "Sunday 5 July", shortLabel: "Sun", isoDate: "2026-07-05", primaryRoundIndex: 3 },
];

export const EVENTS: Record<EventId, EventConfig> = {
  "grand": {
    id: "grand",
    trophySlug: "the-grand-challenge-cup",
    timetableCodes: ["Grand"],
    year: 2026,
    displayName: "Grand Challenge Cup",
    shortLabel: "Grand",
    headerSubtitle: "Live knockout bracket \u00b7 2 crews \u00b7 Premier men's eights",
    crewCount: 2,
    draw: grandDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [1],
    roundLabels: ["Final"],
    seededCrewNumbers: [],
    seededCrewNames: [],
    noRacingNote: "Grand races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "premier-mens-eights",
  },
  "remenham": {
    id: "remenham",
    trophySlug: "the-remenham-challenge-cup",
    timetableCodes: ["Remenham"],
    year: 2026,
    displayName: "Remenham Challenge Cup",
    shortLabel: "Remenham",
    headerSubtitle: "Live knockout bracket \u00b7 2 crews \u00b7 Premier women's eights",
    crewCount: 2,
    draw: remenhamDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [1],
    roundLabels: ["Final"],
    seededCrewNumbers: [],
    seededCrewNames: [],
    noRacingNote: "Remenham races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "premier-womens-eights",
  },
  "lp": {
    id: "lp",
    trophySlug: "the-ladies-challenge-plate",
    timetableCodes: ["Ladies'"],
    year: 2026,
    displayName: "Ladies' Challenge Plate",
    shortLabel: "Ladies",
    headerSubtitle: "Live knockout bracket \u00b7 10 crews \u00b7 Intermediate men's eights",
    crewCount: 10,
    draw: lpDraw as DrawData,
    raceDays: LP_RACE_DAYS,
    roundSizes: [2, 4, 2, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [1, 3, 4, 6],
    seededCrewNames: [],
    noRacingNote: "Ladies' races Thu\u2013Sun \u2014 times publish around 9pm BST the evening before.",
    category: "intermediate-mens-eights",
  },
  "bridge": {
    id: "bridge",
    trophySlug: "the-bridge-challenge-plate",
    timetableCodes: ["Bridge"],
    year: 2026,
    displayName: "Bridge Challenge Plate",
    shortLabel: "Bridge",
    headerSubtitle: "Live knockout bracket \u00b7 10 crews \u00b7 Intermediate women's eights",
    crewCount: 10,
    draw: bridgeDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [2, 4, 2, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [15, 17, 20, 21, 24, 26],
    seededCrewNames: [],
    noRacingNote: "Bridge races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "intermediate-womens-eights",
  },
  "thames": {
    id: "thames",
    trophySlug: "the-thames-challenge-cup",
    timetableCodes: ["Thames"],
    year: 2026,
    displayName: "Thames Challenge Cup",
    shortLabel: "Thames",
    headerSubtitle: "Live knockout bracket \u00b7 32 crews \u00b7 Club men's eights",
    crewCount: 32,
    draw: thamesDraw as DrawData,
    raceDays: PE_RACE_DAYS,
    roundSizes: [16, 8, 4, 2, 1],
    roundLabels: ["1st Round", "2nd Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [27, 31, 33, 39, 41, 42, 44, 45, 48, 50, 59, 61, 62, 63, 67, 70],
    seededCrewNames: [],
    noRacingNote: "Thames races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "club-mens-eights",
  },
  "wargrave": {
    id: "wargrave",
    trophySlug: "the-wargrave-challenge-cup",
    timetableCodes: ["Wargrave"],
    year: 2026,
    displayName: "Wargrave Challenge Cup",
    shortLabel: "Wargrave",
    headerSubtitle: "Live knockout bracket \u00b7 32 crews \u00b7 Club women's eights",
    crewCount: 32,
    draw: wargraveDraw as DrawData,
    raceDays: PE_RACE_DAYS,
    roundSizes: [16, 8, 4, 2, 1],
    roundLabels: ["1st Round", "2nd Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [76, 79, 87, 89, 93, 94, 95, 102, 103, 104, 109],
    seededCrewNames: [],
    noRacingNote: "Wargrave races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "club-womens-eights",
  },
  "temple": {
    id: "temple",
    trophySlug: "the-temple-challenge-cup",
    timetableCodes: ["Temple"],
    year: 2026,
    displayName: "Temple Challenge Cup",
    shortLabel: "Temple",
    headerSubtitle: "Live knockout bracket \u00b7 32 crews \u00b7 Student men's eights",
    crewCount: 32,
    draw: templeDraw as DrawData,
    raceDays: PE_RACE_DAYS,
    roundSizes: [16, 8, 4, 2, 1],
    roundLabels: ["1st Round", "2nd Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [117, 118, 119, 127, 130, 136, 144, 149, 152, 155, 162, 184, 189, 191, 195, 199, 200, 201],
    seededCrewNames: [],
    noRacingNote: "Temple races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "student-mens-eights",
  },
  "island": {
    id: "island",
    trophySlug: "the-island-challenge-cup",
    timetableCodes: ["Island"],
    year: 2026,
    displayName: "Island Challenge Cup",
    shortLabel: "Island",
    headerSubtitle: "Live knockout bracket \u00b7 16 crews \u00b7 Student women's eights",
    crewCount: 16,
    draw: islandDraw as DrawData,
    raceDays: PE_RACE_DAYS,
    roundSizes: [8, 6, 3, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [203, 208, 211, 215, 216, 219, 221, 224, 226, 228, 245, 246, 249, 252],
    seededCrewNames: [],
    noRacingNote: "Island races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "student-womens-eights",
  },
  "pe": {
    id: "pe",
    trophySlug: "the-princess-elizabeth-challenge-cup",
    timetableCodes: ["PE", "P Elizabeth"],
    year: 2026,
    displayName: "Princess Elizabeth Challenge Cup",
    shortLabel: "PE",
    headerSubtitle: "Live knockout bracket \u00b7 32 crews \u00b7 Junior men's eights",
    crewCount: 32,
    draw: peDraw as DrawData,
    raceDays: PE_RACE_DAYS,
    roundSizes: [16, 8, 4, 2, 1],
    roundLabels: ["1st Round", "2nd Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [256, 263, 270, 273, 281, 282, 283, 284, 286, 288, 290, 300],
    seededCrewNames: [],
    noRacingNote: "PE has no racing on Thursday \u2014 Friday times publish around 9pm BST the evening before.",
    category: "junior-mens-eights",
  },
  "prince-philip": {
    id: "prince-philip",
    trophySlug: "the-prince-philip-challenge-trophy",
    timetableCodes: ["P Philip"],
    year: 2026,
    displayName: "Prince Philip Challenge Trophy",
    shortLabel: "P Philip",
    headerSubtitle: "Live knockout bracket \u00b7 16 crews \u00b7 Junior women's eights",
    crewCount: 16,
    draw: prince_philipDraw as DrawData,
    raceDays: PE_RACE_DAYS,
    roundSizes: [8, 8, 4, 2, 1],
    roundLabels: ["1st Round", "Last 16", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [306, 307, 308, 309, 311, 313, 314, 315, 318, 323, 324, 327, 328, 329, 334, 339],
    seededCrewNames: [],
    noRacingNote: "P Philip races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "junior-womens-eights",
  },
  "stewards": {
    id: "stewards",
    trophySlug: "the-stewards-challenge-cup",
    timetableCodes: ["Stewards"],
    year: 2026,
    displayName: "Stewards' Challenge Cup",
    shortLabel: "Stewards",
    headerSubtitle: "Live knockout bracket \u00b7 3 crews \u00b7 Premier men's coxless fours",
    crewCount: 3,
    draw: stewardsDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [1, 1],
    roundLabels: ["Semi-Final", "Final"],
    seededCrewNumbers: [],
    seededCrewNames: [],
    noRacingNote: "Stewards races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "premier-mens-coxless-fours",
  },
  "town": {
    id: "town",
    trophySlug: "the-town-challenge-cup",
    timetableCodes: ["Town"],
    year: 2026,
    displayName: "Town Challenge Cup",
    shortLabel: "Town",
    headerSubtitle: "Live knockout bracket \u00b7 9 crews \u00b7 Premier women's coxless fours",
    crewCount: 9,
    draw: townDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [1, 4, 2, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [],
    seededCrewNames: [],
    noRacingNote: "Town races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "premier-womens-coxless-fours",
  },
  "visitors": {
    id: "visitors",
    trophySlug: "the-visitors-challenge-cup",
    timetableCodes: ["Visitors'"],
    year: 2026,
    displayName: "Visitors' Challenge Cup",
    shortLabel: "Visitors",
    headerSubtitle: "Live knockout bracket \u00b7 12 crews \u00b7 Intermediate men's coxless fours",
    crewCount: 12,
    draw: visitorsDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [4, 4, 2, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [352, 355, 356, 358, 359, 362, 364, 367],
    seededCrewNames: [],
    noRacingNote: "Visitors races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "intermediate-mens-coxless-fours",
  },
  "wyfold": {
    id: "wyfold",
    trophySlug: "the-wyfold-challenge-cup",
    timetableCodes: ["Wyfold"],
    year: 2026,
    displayName: "Wyfold Challenge Cup",
    shortLabel: "Wyfold",
    headerSubtitle: "Live knockout bracket \u00b7 32 crews \u00b7 Club coxless fours",
    crewCount: 32,
    draw: wyfoldDraw as DrawData,
    raceDays: PE_RACE_DAYS,
    roundSizes: [16, 8, 4, 2, 1],
    roundLabels: ["1st Round", "2nd Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [383, 388, 392, 393, 395, 397, 400, 401, 405, 409, 413, 415, 416, 420],
    seededCrewNames: [],
    noRacingNote: "Heats run Tue\u2013Wed; knockout continues Fri\u2013Sun \u2014 times publish around 9pm BST the evening before.",
    category: "club-coxless-fours",
  },
  "queen-mother": {
    id: "queen-mother",
    trophySlug: "the-queen-mother-challenge-cup",
    timetableCodes: ["Q Mother"],
    year: 2026,
    displayName: "Queen Mother Challenge Cup",
    shortLabel: "Q Mother",
    headerSubtitle: "Live knockout bracket \u00b7 5 crews \u00b7 Premier men's quadruple sculls",
    crewCount: 5,
    draw: queen_motherDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [1, 2, 1],
    roundLabels: ["Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [],
    seededCrewNames: [],
    noRacingNote: "Q Mother races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "premier-mens-quads",
  },
  "princess-grace": {
    id: "princess-grace",
    trophySlug: "the-princess-grace-challenge-cup",
    timetableCodes: ["P Grace"],
    year: 2026,
    displayName: "Princess Grace Challenge Cup",
    shortLabel: "P Grace",
    headerSubtitle: "Live knockout bracket \u00b7 2 crews \u00b7 Premier women's quadruple sculls",
    crewCount: 2,
    draw: princess_graceDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [1],
    roundLabels: ["Final"],
    seededCrewNumbers: [],
    seededCrewNames: [],
    noRacingNote: "P Grace races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "premier-womens-quads",
  },
  "pow": {
    id: "pow",
    trophySlug: "the-prince-of-wales-challenge-cup",
    timetableCodes: ["Pr Wales"],
    year: 2026,
    displayName: "Prince of Wales Challenge Cup",
    shortLabel: "POW",
    headerSubtitle: "Live knockout bracket \u00b7 16 crews \u00b7 Intermediate men's quadruple sculls",
    crewCount: 16,
    draw: powDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [8, 4, 2, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [434, 443, 446, 450],
    seededCrewNames: [],
    noRacingNote: "Races Thu\u2013Sun \u2014 times publish around 9pm BST the evening before.",
    category: "intermediate-mens-quads",
  },
  "princess-of-wales": {
    id: "princess-of-wales",
    trophySlug: "the-princess-of-wales-challenge-trophy",
    timetableCodes: ["P Wales"],
    year: 2026,
    displayName: "Princess of Wales Challenge Trophy",
    shortLabel: "P Wales",
    headerSubtitle: "Live knockout bracket \u00b7 8 crews \u00b7 Intermediate women's quadruple sculls",
    crewCount: 8,
    draw: princess_of_walesDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [4, 2, 1],
    roundLabels: ["Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [462, 463, 464, 465, 471],
    seededCrewNames: [],
    noRacingNote: "P Wales races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "intermediate-womens-quads",
  },
  "danesfield": {
    id: "danesfield",
    trophySlug: "the-danesfield-challenge-cup",
    timetableCodes: ["Danesfield"],
    year: 2026,
    displayName: "Danesfield Challenge Cup",
    shortLabel: "Danesfield",
    headerSubtitle: "Live knockout bracket \u00b7 16 crews \u00b7 Club women's quadruple sculls",
    crewCount: 16,
    draw: danesfieldDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [8, 4, 2, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [481, 485, 486, 489, 491, 500, 501, 502],
    seededCrewNames: [],
    noRacingNote: "Danesfield races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "club-womens-quads",
  },
  "queen-victoria": {
    id: "queen-victoria",
    trophySlug: "the-queen-victoria-challenge-cup",
    timetableCodes: ["Q Victoria"],
    year: 2026,
    displayName: "Queen Victoria Challenge Cup",
    shortLabel: "Q Victoria",
    headerSubtitle: "Live knockout bracket \u00b7 10 crews \u00b7 Student women's quadruple sculls",
    crewCount: 10,
    draw: queen_victoriaDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [2, 4, 2, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [512, 514, 516, 526, 527, 531],
    seededCrewNames: [],
    noRacingNote: "Q Victoria races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "student-womens-quads",
  },
  "fawley": {
    id: "fawley",
    trophySlug: "the-fawley-challenge-cup",
    timetableCodes: ["Fawley"],
    year: 2026,
    displayName: "Fawley Challenge Cup",
    shortLabel: "Fawley",
    headerSubtitle: "Live knockout bracket \u00b7 32 crews \u00b7 Junior men's quadruple sculls",
    crewCount: 32,
    draw: fawleyDraw as DrawData,
    raceDays: PE_RACE_DAYS,
    roundSizes: [16, 8, 4, 2, 1],
    roundLabels: ["1st Round", "2nd Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [538, 541, 546, 552, 553, 556, 565, 570, 579, 582, 586, 591, 597, 598, 600],
    seededCrewNames: [],
    noRacingNote: "Fawley races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "junior-mens-quads",
  },
  "diamond-jubilee": {
    id: "diamond-jubilee",
    trophySlug: "the-diamond-jubilee-challenge-cup",
    timetableCodes: ["D Jubilee"],
    year: 2026,
    displayName: "Diamond Jubilee Challenge Cup",
    shortLabel: "D Jubilee",
    headerSubtitle: "Live knockout bracket \u00b7 16 crews \u00b7 Junior women's quadruple sculls",
    crewCount: 16,
    draw: diamond_jubileeDraw as DrawData,
    raceDays: PE_RACE_DAYS,
    roundSizes: [8, 4, 2, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [609, 612, 615, 617, 629, 630, 632, 637, 641, 643, 644, 645, 648, 653, 655, 659],
    seededCrewNames: [],
    noRacingNote: "D Jubilee races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "junior-womens-quads",
  },
  "britannia": {
    id: "britannia",
    trophySlug: "the-britannia-challenge-cup",
    timetableCodes: ["Britannia"],
    year: 2026,
    displayName: "Britannia Challenge Cup",
    shortLabel: "Britannia",
    headerSubtitle: "Live knockout bracket \u00b7 16 crews \u00b7 Club coxed fours",
    crewCount: 16,
    draw: britanniaDraw as DrawData,
    raceDays: PE_RACE_DAYS,
    roundSizes: [8, 4, 2, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [677, 679, 682, 683, 688, 693],
    seededCrewNames: [],
    noRacingNote: "Britannia races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "club-coxed-fours",
  },
  "prince-albert": {
    id: "prince-albert",
    trophySlug: "the-prince-albert-challenge-cup",
    timetableCodes: ["P Albert"],
    year: 2026,
    displayName: "Prince Albert Challenge Cup",
    shortLabel: "P Albert",
    headerSubtitle: "Live knockout bracket \u00b7 8 crews \u00b7 Student men's coxed fours",
    crewCount: 8,
    draw: prince_albertDraw as DrawData,
    raceDays: PE_RACE_DAYS,
    roundSizes: [4, 2, 1],
    roundLabels: ["Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [704, 709, 716, 717, 721, 724, 727, 728, 730, 736, 744],
    seededCrewNames: [],
    noRacingNote: "P Albert races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "student-mens-coxed-fours",
  },
  "goblets": {
    id: "goblets",
    trophySlug: "the-silver-goblets-and-nickalls-challenge-cup",
    timetableCodes: ["Goblets"],
    year: 2026,
    displayName: "Silver Goblets & Nickalls' Challenge Cup",
    shortLabel: "Goblets",
    headerSubtitle: "Live knockout bracket \u00b7 8 crews \u00b7 Premier men's coxless pairs",
    crewCount: 8,
    draw: gobletsDraw as DrawData,
    raceDays: GOBLETS_RACE_DAYS,
    roundSizes: [4, 2, 1],
    roundLabels: ["Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [749, 751, 759, 761],
    seededCrewNames: [],
    noRacingNote: "Goblets races Fri\u2013Sun \u2014 times publish around 9pm BST the evening before.",
    category: "premier-mens-coxless-pairs",
  },
  "hambleden-pairs": {
    id: "hambleden-pairs",
    trophySlug: "the-hambleden-pairs-challenge-cup",
    timetableCodes: ["Hambleden"],
    year: 2026,
    displayName: "Hambleden Pairs Challenge Cup",
    shortLabel: "Hambleden",
    headerSubtitle: "Live knockout bracket \u00b7 8 crews \u00b7 Premier women's coxless pairs",
    crewCount: 8,
    draw: hambleden_pairsDraw as DrawData,
    raceDays: GOBLETS_RACE_DAYS,
    roundSizes: [4, 2, 1],
    roundLabels: ["Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [765, 767, 769, 770, 772, 774],
    seededCrewNames: [],
    noRacingNote: "Hambleden races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "premier-womens-coxless-pairs",
  },
  "double-sculls": {
    id: "double-sculls",
    trophySlug: "the-double-sculls-challenge-cup",
    timetableCodes: ["Doubles"],
    year: 2026,
    displayName: "Double Sculls Challenge Cup",
    shortLabel: "Doubles",
    headerSubtitle: "Live knockout bracket \u00b7 8 crews \u00b7 Premier men's double sculls",
    crewCount: 8,
    draw: double_scullsDraw as DrawData,
    raceDays: GOBLETS_RACE_DAYS,
    roundSizes: [4, 2, 1],
    roundLabels: ["Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [777, 780, 781, 782, 783, 784, 787, 789, 790],
    seededCrewNames: [],
    noRacingNote: "Doubles races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "premier-mens-doubles",
  },
  "stonor": {
    id: "stonor",
    trophySlug: "the-stonor-challenge-trophy",
    timetableCodes: ["Stonor"],
    year: 2026,
    displayName: "Stonor Challenge Trophy",
    shortLabel: "Stonor",
    headerSubtitle: "Live knockout bracket \u00b7 8 crews \u00b7 Premier women's double sculls",
    crewCount: 8,
    draw: stonorDraw as DrawData,
    raceDays: GOBLETS_RACE_DAYS,
    roundSizes: [4, 2, 1],
    roundLabels: ["Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [],
    seededCrewNames: [],
    noRacingNote: "Stonor races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "premier-womens-doubles",
  },
  "diamond": {
    id: "diamond",
    trophySlug: "the-diamond-challenge-sculls",
    timetableCodes: ["Diamonds", "D Sculls"],
    year: 2026,
    displayName: "Diamond Challenge Sculls",
    shortLabel: "Diamond",
    headerSubtitle: "Live knockout bracket \u00b7 16 crews \u00b7 Premier men's single sculls",
    crewCount: 16,
    draw: diamondDraw as DrawData,
    raceDays: POW_RACE_DAYS,
    roundSizes: [8, 4, 2, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [813, 818, 819, 820, 830, 831, 832, 840],
    seededCrewNames: [],
    noRacingNote: "Diamond races Thu\u2013Sun \u2014 times publish around 9pm BST the evening before.",
    category: "premier-mens-sculls",
  },
  "princess-royal": {
    id: "princess-royal",
    trophySlug: "the-princess-royal-challenge-cup",
    timetableCodes: ["P Royal"],
    year: 2026,
    displayName: "Princess Royal Challenge Cup",
    shortLabel: "P Royal",
    headerSubtitle: "Live knockout bracket \u00b7 12 crews \u00b7 Premier women's single sculls",
    crewCount: 12,
    draw: princess_royalDraw as DrawData,
    raceDays: GOBLETS_RACE_DAYS,
    roundSizes: [4, 4, 2, 1],
    roundLabels: ["1st Round", "Quarter-Final", "Semi-Final", "Final"],
    seededCrewNumbers: [842, 848, 849, 850, 852, 853, 854, 856, 859],
    seededCrewNames: [],
    noRacingNote: "P Royal races per HRR schedule \u2014 times publish around 9pm BST the evening before.",
    category: "premier-womens-sculls",
  },
};

export const EVENT_LIST: EventConfig[] = (
  [
    EVENTS["grand"],
    EVENTS["remenham"],
    EVENTS["lp"],
    EVENTS["bridge"],
    EVENTS["thames"],
    EVENTS["wargrave"],
    EVENTS["temple"],
    EVENTS["island"],
    EVENTS["pe"],
    EVENTS["prince-philip"],
    EVENTS["stewards"],
    EVENTS["town"],
    EVENTS["visitors"],
    EVENTS["wyfold"],
    EVENTS["queen-mother"],
    EVENTS["princess-grace"],
    EVENTS["pow"],
    EVENTS["princess-of-wales"],
    EVENTS["danesfield"],
    EVENTS["queen-victoria"],
    EVENTS["fawley"],
    EVENTS["diamond-jubilee"],
    EVENTS["britannia"],
    EVENTS["prince-albert"],
    EVENTS["goblets"],
    EVENTS["hambleden-pairs"],
    EVENTS["double-sculls"],
    EVENTS["stonor"],
    EVENTS["diamond"],
    EVENTS["princess-royal"],
  ] as EventConfig[]
).sort(compareEventsForSelector);

export function getEventConfig(id: string): EventConfig | null {
  if (id in EVENTS) return EVENTS[id as EventId];
  return null;
}

export function isEventId(id: string): id is EventId {
  return id in EVENTS;
}
